Revert of Enable public key pinning of local trust anchors (patchset #5 id:80001 of https://codereview.chromium.org/2052363002/ )
Reason for revert:
Android Bot Compilation failure:

../../components/cronet/android/test/javaperftests/src/org/chromium/net/CronetPerfTestActivity.java:196: error: method createMockCertVerifier in class MockCertVerifier cannot be applied to given types;

https://build.chromium.org/p/chromium/builders/Android/builds/58499/steps/compile/logs/stdio

Original issue's description:
> Enable public key pinning of local trust anchors
>
> Provides a new API that allows Cronet client to enable public key pinning of local trust anchors, i.e. pinning of certificates added to the local user trust store.
>
> /**
>  * Enables or disables pinning of the local (user-level) trust anchors.
>  *
>  * @param value {@code true} to enable pinning, {@code false} to disable.
>  * @return the builder to facilitate chaining.
>  */
>  public Builder enablePublicKeyPinsForLocalTrustAnchors(boolean value);
>
> BUG=606832
>
> Committed: https://crrev.com/9cf8e6f923a9b472c8b3521d52b3b6ca910f77cf
> Cr-Commit-Position: refs/heads/master@{#403486}

TBR=rsleevi@chromium.org,mef@chromium.org,xunjieli@chromium.org,kapishnikov@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=606832

Review-Url: https://codereview.chromium.org/2117763004
Cr-Original-Commit-Position: refs/heads/master@{#403498}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 025788d30fdf38744ebe718d8d8ecd5da161f8a9