Revert 218672 "Add unittests for X509Certificate::GetPublicKeyInfo"
The tests failed on "net_unittests" on "XP Tests (dbg)(2)".
The URL with results is http://build.chromium.org/p/chromium.win/builders/XP%20Tests%20%28dbg%29%282%29/builds/32492, and the log output for the test is:

X509CertificatePublicKeyInfoTest.GetPublicKeyInfo/2: 
cert\x509_certificate_unittest.cc(1176): error: Value of: actual_bits
Actual: 0
Expected: data.expected_bits
Which is: 256
cert\x509_certificate_unittest.cc(1177): error: Value of: actual_type
Actual: 0
Expected: data.expected_type
Which is: 3

> Add unittests for X509Certificate::GetPublicKeyInfo
> 
> This was already implicitly tested by the WeakKey tests, but add simple
> explicit tests for GetPublicKeyInfo
> 
> BUG=257119
> R=wtc@chromium.org
> 
> Review URL: https://chromiumcodereview.appspot.com/23059003

TBR=rsleevi@chromium.org

Review URL: https://codereview.chromium.org/23359004

git-svn-id: http://src.chromium.org/svn/trunk/src/net@218678 4ff67af0-8c30-449e-8e8b-ad334ec8d88c