net: chromeos build fix about AddressTrackerLinux
clang complains it doesn't initialize const member, so this CL calls the
default constructor explicitly.

../../net/base/address_tracker_linux.cc:113:22: error: constructor for 'net::internal::AddressTrackerLinux' must explicitly initialize the const member 'ignored_interfaces_'
AddressTrackerLinux::AddressTrackerLinux()
                     ^
../../net/base/address_tracker_linux.h:166:37: note: 'ignored_interfaces_' declared here
  const base::hash_set<std::string> ignored_interfaces_;
                                    ^

Review URL: https://codereview.chromium.org/1652683002

Cr-Original-Commit-Position: refs/heads/master@{#372929}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 425c26974398ffb129887d6b2e816befc6e93a26