Attempt to fix Linux Tests (dbg) bot.
Fails with:
../../net/test/cert_test_util_nss.cc:36:error: undefined reference to 'crypto::RSAPrivateKey::CreateSensitiveFromPrivateKeyInfo(PK11SlotInfoStr*, std::__debug::vector<unsigned char, std::allocator<unsigned char> > const&)'
../../net/test/cert_test_util_nss.cc:47:error: undefined reference to 'crypto::AutoNSSWriteLock::AutoNSSWriteLock()'
../../net/test/cert_test_util_nss.cc:57:error: undefined reference to 'crypto::AutoNSSWriteLock::~AutoNSSWriteLock()'
../../base/memory/scoped_ptr.h:127:error: undefined reference to 'crypto::RSAPrivateKey::~RSAPrivateKey()'

net_test_support's cert_test_util_nss.cc does call these functions and
net_test_support doesn't depend on crypto, so add this missing dep.
It's a bit of a mystery why this happens when linking views_content_client
though, as that shouldn't depend on test code (and I'm not near a linux
box, so I can't ask tools/gyp-explain -- will check on monday.)

BUG=371125
R=timloh@chromium.org
TBR=rsleevi@chromium.org

Review URL: https://codereview.chromium.org/822483008

Cr-Original-Commit-Position: refs/heads/master@{#312072}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: ab3090304649f96826175fc6a553fd0b6793bd5d