Revert of Remove header dependencies from sequence_checker.h to sequenced_worker_pool.h (patchset #6 id:470001 of https://codereview.chromium.org/2690533002/ )
Reason for revert:
This patch is causing failures on the CrOS build bot:

../../chrome/browser/chromeos/login/wizard_controller.cc:225:42: error: member access into incomplete type 'base::SequencedWorkerPool'
  DCHECK(BrowserThread::GetBlockingPool()->RunsTasksOnCurrentThread());
                                         ^
../../base/threading/thread_restrictions.h:93:7: note: forward declaration of 'base::SequencedWorkerPool'
class SequencedWorkerPool;
      ^
1 error generated.

Original issue's description:
> Remove header dependencies from sequence_checker.h to sequenced_worker_pool.h
>
> This CL removes #include to sequenced_worker_pool.h in sequence_checker.h
> by hiding its members into a nested class, and adds #include and forward
> decls to other files as needed.
>
> Note that the non trivial diffs are in sequence_checker_impl.{h,cc} only.
>
> The header dependency from sequence_checker.h to sequenced_worker_pool.h
> prevents other headers to use sequence_checker.h due to a dependency
> cycle.
>
> TBR=sky@chromium.org, kinuko@chromium.org, rdsmith@chromium.org, qinmin@chromium.org, marq@chromium.org, rockot@chromium.org, blundell@chromium.org, oshima@chromium.org, slan@chromium.org, boliu@chromium.org
>
> Review-Url: https://codereview.chromium.org/2690533002
> Cr-Original-Commit-Position: refs/heads/master@{#450321}
> Committed: https://chromium.googlesource.com/chromium/src/+/d502a3f2fa0b673a5082c1d601298bd114a9d237
> Review-Url: https://codereview.chromium.org/2690533002
> Cr-Commit-Position: refs/heads/master@{#450384}
> Committed: https://chromium.googlesource.com/chromium/src/+/70b7c5d796420107930c72d4ad82e0c850166b1a

TBR=gab@chromium.org,sky@chromium.org,kinuko@chromium.org,rdsmith@chromium.org,qinmin@chromium.org,marq@chromium.org,rockot@chromium.org,blundell@chromium.org,oshima@chromium.org,slan@chromium.org,boliu@chromium.org,msramek@chromium.org,tzik@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true

Review-Url: https://codereview.chromium.org/2694813005
Cr-Original-Commit-Position: refs/heads/master@{#450402}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 72c70c9d1f6b5453aeb518610b2fa581bed511aa