Revert of Test dead code. (patchset #4 id:60001 of https://codereview.chromium.org/988733003/)
Reason for revert:
Broke "compile" on "iOS_Device".

http://build.chromium.org/p/chromium.mac/builders/iOS_Device/builds/26659/steps/compile/logs/stdio

Undefined symbols for architecture armv7:
  "net::SpdyPriorityIR::SpdyPriorityIR(unsigned int, unsigned int, unsigned char, bool)", referenced from:
      net::SpdyFramerTest_CreatePriority_Test::TestBody() in spdy_framer_test.o
      net::SpdyFramerTest_ReadPriority_Test::TestBody() in spdy_framer_test.o
ld: symbol(s) not found for architecture armv7
clang:error: linker command failed with exit code 1 (use -v to see invocation)

Original issue's description:
> Test dead code.
>
> Test a log method that could be helpful for debugging.  Also inline SpdyPriorityIR constructors for code convergence.
>
> This CL lands server change 87053738 by birenroy.
>
> BUG=
>
> Committed: https://crrev.com/e44eb0a35c11f8ff743873f5f382b5d5c5353325
> Cr-Commit-Position: refs/heads/master@{#319724}

TBR=rch@chromium.org,bnc@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=

Review URL: https://codereview.chromium.org/992613005

Cr-Original-Commit-Position: refs/heads/master@{#319735}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 2136db0ac1af67ab3981249a2c15c2dee8e851d2